### ISSUE TITLE
Error when attempting to create a migration

### ISSUE THREAD

**Issue by ricardojmendez** [yogthos/migratus-lein#7]
Using Clojure 1.7.0, plugin migratus-lein 0.1.3 and migratus 0.8.0:

```
$ lein migratus create add-test-table
creating migration files for (add-test-table)
Exception in thread "main" java.lang.RuntimeException: No such var: migratus.core/create, compiling:(/private/var/folders/64/ckdtdxm14059n9wh8rhf1mvw0000gn/T/form-init4079916481944837462.clj:1:279)
	at clojure.lang.Compiler.analyze(Compiler.java:6543)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3737)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.eval(Compiler.java:6779)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: migratus.core/create
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6993)
	at clojure.lang.Compiler.resolve(Compiler.java:6963)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
	at clojure.lang.Compiler.analyze(Compiler.java:6506)
	... 24 more
Subprocess failed
```

**Comment by ricardojmendez** [comment]
This issue disappears when using migratus 0.8.1.

**Comment by wmealing** [comment]
Confirmed same behavior, also fixed with upgrade.
